/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FtModal {
    }
}
export interface FtModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFtModalElement;
}
declare global {
    interface HTMLFtModalElement extends Components.FtModal, HTMLStencilElement {
    }
    var HTMLFtModalElement: {
        prototype: HTMLFtModalElement;
        new (): HTMLFtModalElement;
    };
    interface HTMLElementTagNameMap {
        "ft-modal": HTMLFtModalElement;
    }
}
declare namespace LocalJSX {
    interface FtModal {
        "onConfirm"?: (event: FtModalCustomEvent<null>) => void;
    }
    interface IntrinsicElements {
        "ft-modal": FtModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ft-modal": LocalJSX.FtModal & JSXBase.HTMLAttributes<HTMLFtModalElement>;
        }
    }
}
